export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL';

export const GET_PRODUCT_DETAILS_REQUEST =
  'GET_PRODUCT_DETAILS_REQUEST';
export const GET_PRODUCT_DETAILS_SUCCESS =
  'GET_PRODUCT_DETAILS_SUCCESS';
export const GET_PRODUCTS_DETAILS_FAIL =
  'GET_PRODUCTS_DETAILS_FAIL';

export const FILTER_PRODUCTS = 'FILTER_PRODUCTS';

// user Registration
export const REGISTER_USER_REQUEST =
  'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS =
  'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';

// Authenticate User
export const USER_AUTH_REQUEST = 'USER_AUTH_REQUEST';
export const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS';
export const USER_SIGN_OUT = 'USER_SIGN_OUT';
export const USER_AUTH_FAIL = 'USER_AUTH_FAIL';

export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const REMOVE_PRODUCT_FROM_CART =
  'REMOVE_PRODUCT_FROM_CART';

export const INCREASE_CART_QTY = 'INCREASE_CART_QTY';
export const DECREASE_CART_QTY = 'DECREASE_CART_QTY';
